# Navigation
nav:
  - Home: 'index.md'
  - Linux:
      - General: 'linux/general/general.md'
      - Files: 'linux/general/files.md'
      - Memory & Swap: 'linux/general/memorySwap.md'
      - Guides:
            - Python Simple Web-Server: 'linux/linuxGuides/pythonWebServer.md'
            - Resize Root PartitionWithout Reboot: 'linux/linuxGuides/ResizeRootPartitionWithoutReboot.md'
            - Installing Oh My zsh: 'linux/linuxGuides/zshOnSteroids.md'
      - cPanel & WHM: 'linux/cpanel.md'
      - CSF Firewall: 'linux/csf.md'
      - Nginx: 'linux/nginx.md'
      - Apache: 'linux/apache.md'
      - Sophos Firewall: 'linux/sophos.md'
      - Wordpress: 'linux/wordpress.md'
      - Esxi: 'linux/esxi.md'
      - Ples: 'linux/plesk.md'
  - macOS:
      - General: 'macOS/macGeneral.md'
      - Home Brew: 'macOS/brew.md'
      - MacOS Swoftware: 'macOS/macSoftware.md'
      - Alftred Workflows: 'macOS/alfredWorkFlows.md'
  - Rasperry Pi:
      - General: 'rasperryPi/piGeneral.md'
      - Rasperry Pi 3 Tor Access Point: 'rasperryPi/TOR-Pi.md'
      - Rasperry Pi Magic Mirror: 'rasperryPi/MagicMirror.md'
  - Development:
      - Python: 'development/python.md'
  - Windows:
      - Useful Links for Windows: 'windows/winGeneral.md'
      - Software for Windows: 'windows/winSoftware.md'
  - Browsers Extensions:
      - Chrome: 'browsers/chromeExtensions.md'
      - Firefox: 'browsers/firefoxExtentions.md'
  - Android:
      - Useful Apps for Android: 'android/androidApps.md'
  - Penetration-Testing:
      - General: 'penTesting/penTestingGeneral.md'
      - Kali Linux Modifications: 'penTesting/KaliLinux.md'
      - Installing Bettercap 1.6.2: penTesting/bettercao1.6.2.md
  - Other:
      - General: 'general/generalLinks.md'
      - Gmail Mark As Read Script: 'general/gmailMarkAsRead.md'
      - Synology DSM : 'general/synologyGeneral.md'
      - Ubiquiti Networking: 'general/ubiquiti.md'
      - WiFi QR Generator: 'general/qrwifi/index.html'
  - Help:
      - Documinatation: 'help/documinatation.md'
      - Basic Cheat-Sheet: 'help/markdown_cheatsheet_basic.md'
      - MarkDown Cheat-Sheet: 'help/markdown_cheat-sheet.md'
      - Admonitions, callouts, sidebars: 'help/blocks.md'
  - About: 'about.md'

# Site information
site_name: '3os.org'
site_url: 'https://3os.org/'
site_description: 'Collocation of Guide, Technical knowledge, Security, Exmaples, Tips, at any operating system'
site_author: 'Stas Kosatuhin'

# Repository Link Editor
repo_url: 'https://github.com/fire1ce/3os.org/'
edit_uri: 'edit/master/docs/'

# Theme Configuration
theme:
  name: 'material'
  logo: 'images/logo.png'
  favicon: 'images/favicon.ico'
  palette:
    primary: 'teal'
    accent: 'teal'
  feature:
    tabs: 'true'
  # font:
  #   text: 'Roboto Slab'
  #   code: 'Roboto Mono'

# Social Links and Comments
extra:
  disqus: '3os'
  social:
    - type: 'github'
      link: 'https://github.com/fire1ce'
    - type: 'linkedin'
      link: 'https://linkedin.com/in/stas-kosatuhin
'

# Markdown Rendering Extensions
markdown_extensions:
  - toc:
        permalink: True
        separator: "_"
  - admonition
  - codehilite
  - footnotes
  - meta
  - sane_lists
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.extra

# Google Analytics
google_analytics:
  - 'UA-122318911-1'
  - 'auto'