# Main MkDocs Config file

# Navigation
nav:
  - Home: 'index.md'
  - Contributions Wall: 'contributions.md'
  - Changelog: 'CHANGELOG.md'
  - Donate: 'donation.md'
  - Linux:
      - General: 'linux/general/general.md'
      - SSH Service Security: 'linux/SSH_Service_Security.md'
      - Centos 7: 'linux/centos7.md'
      - Ubuntu: 'linux/ubuntu.md'
      - Files: 'linux/general/files.md'
      - Memory & Swap: 'linux/general/memorySwap.md'
      - Linux LVM Partitions: 'linux/lvm.md'
      - Guides:
            - Resize Root PartitionWithout Reboot: 'linux/linuxGuides/ResizeRootPartitionWithoutReboot.md'
            - Installing Oh My zsh: 'linux/linuxGuides/zshOnSteroids.md'
      - Linux Services:
            - cPanel & WHM: 'linux/services/cpanel.md'
            - CSF Firewall: 'linux/services/csf.md'
            - Nginx: 'linux/services/nginx.md'
            - Apache: 'linux/services/apache.md'
            - Sophos Firewall: 'linux/services/sophos.md'
            - Wordpress: 'linux/services/wordpress.md'
            - Esxi: 'linux/services/esxi.md'
            - Plesk: 'linux/services/plesk.md'
  - macOS:
      - General: 'macOS/macGeneral.md'
      - BetterTerminal Fule Gide: 'macOS/BetterTerminal.md'
      - Brew: 'macOS/brew.md'
      - Alftred Workflows: 'macOS/alfredWorkFlows.md'
  - Raspberry Pi:
      - General: 'raspberryPi/piGeneral.md'
      - Raspberry Pi 3 Tor Access Point: 'raspberryPi/TOR-Pi.md'
      - raspberry Pi Magic Mirror: 'raspberryPi/MagicMirror.md'
  - Development:
      - Git: development/git.md
      - Docker: 'development/docker.md'
      - Python: 'development/python.md'
      - Ruby: 'development/ruby.md'
      - npm: 'development/npm.md'
      - MongoDB: 'development/mongodb.md'
  - Windows:
      - Windows General: 'windows/windowsGeneral.md'
      - Windows Guides and How-To: 'windows/windowsGuides.md'
  - Penetration-Testing:
      - General: 'penTesting/penTestingGeneral.md'
      - Click-Jacking Test: 'penTesting/clickJacking.md'
      - Israel ID Generator & Validator: 'penTesting/IDD_Generator.md'
      - Android Penetration Testing: 'penTesting/androidPT.md'
      - Kali linux Modifications: 'penTesting/kaliLinux.md'
      - Installing Bettercap 1.6.2: 'penTesting/bettercao1.6.2.md'
  - More Categories:
      - General: 'moreCategories/generalLinks.md'
      - Browsers Extensions:
             - Chrome: 'moreCategories/browsers/chromeExtensions.md'
             - Firefox: 'moreCategories/browsers/firefoxExtentions.md'
      - Synology DSM : 'moreCategories/synology.md'
      - Ubiquiti Networking: 'moreCategories/ubiquiti.md'
      - Android: 'moreCategories/android.md'
      - WiFi QR Generator: 'moreCategories/wifiQrGenerator.md'
      - Home Assistent: 'moreCategories/homeAssistent.md'
      - Gmail Mark As Read Script: 'moreCategories/gmailMarkAsRead.md'
  - Markdown CheatSheet:
      - Welcome: 'markdownCheatSheet/welcome.md'
      - Headings: 'markdownCheatSheet/headings.md'
      - Emphasis: 'markdownCheatSheet/emphasis.md'
      - Line Breaks: 'markdownCheatSheet/lineBreaks.md'
      - Lists: 'markdownCheatSheet/lists.md'
      - Tables: 'markdownCheatSheet/tables.md'
      - Links: 'markdownCheatSheet/links.md'
      - Images: 'markdownCheatSheet/images.md'
      - Admonition: 'markdownCheatSheet/admonition.md'
      - Block Quotes: 'markdownCheatSheet/blockQuotes.md'
      - Emojis List: 'markdownCheatSheet/emoji.md'
      - Embed External Sources:
            - Gists: 'markdownCheatSheet/embedGists.md'
            - YouTube Videos: 'markdownCheatSheet/embedYouTubeVideos.md'
            - Lucid Chart: 'markdownCheatSheet/embedLucidChart.md'
      - Simple Template: 'markdownCheatSheet/template.md'
      - Extra:
            - Metadata Per Page: 'markdownCheatSheet/metaData.md'


# Site information
site_name: '3os.org'
site_url: 'https://3os.org/'
site_description: 'Collocation of Guide, Technical knowledge, Security, Examples, Tips, at any operating system'
site_author: 'Stas Kosatuhin'

# Repository Link Editor
repo_name: 'fire1ce/3os.org'
repo_url: 'https://github.com/fire1ce/3os.org/'
edit_uri: 'edit/master/src/'

# Theme Configuration
docs_dir: src
theme:
  name: 'material'
  language: en
  logo:
    icon: 'donut_small'
  favicon: 'assets/images/favicon.ico'
  palette:
    primary: 'teal'
    accent: 'teal'
  feature:
    tabs: 'true'
  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'

# Social Links and Comments
extra:
  disqus: '3os'
  search:
    tokenizer: '[\s\-\.]+'
  social:
    - type: 'github'
      link: 'https://github.com/fire1ce'
    - type: 'linkedin'
      link: 'https://linkedin.com/in/stas-kosatuhin'

extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'

# Markdown Rendering Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.sane_lists
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.def_list
  - markdown.extensions.abbr
  - markdown.extensions.tables
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.toc:
      permalink: True
      separator: "_"
  - pymdownx.extra
  - pymdownx.arithmatex
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tilde
  - pyembed.markdown
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg

  # list of extensions https://github.com/Python-Markdown/markdown/wiki/Third-Party-Extensions

# Google Analytics
google_analytics:
  - 'UA-122318911-1'
  - 'auto'

# Copyright
copyright: 'Copyright &copy; Stas Kosatuhin @2018'