# Navigation
nav:
  - Home: 'index.md'
  - Changelog: 'CHANGELOG.md'
  - Linux:
      - SSH Service Security: 'Linux/SSH_Service_Security.md'
      - General: 'Linux/general/general.md'
      - Files: 'Linux/general/files.md'
      - Memory & Swap: 'Linux/general/memorySwap.md'
      - Guides:
            - Python Simple Web-Server: 'Linux/linuxGuides/pythonWebServer.md'
            - Resize Root PartitionWithout Reboot: 'Linux/linuxGuides/ResizeRootPartitionWithoutReboot.md'
            - Installing Oh My zsh: 'Linux/linuxGuides/zshOnSteroids.md'
      - Linux-Services:
            - cPanel & WHM: 'Linux/Services/cpanel.md'
            - CSF Firewall: 'Linux/Services/csf.md'
            - Nginx: 'Linux/Services/nginx.md'
            - Apache: 'Linux/Services/apache.md'
            - Sophos Firewall: 'Linux/Services/sophos.md'
            - Wordpress: 'Linux/Services/wordpress.md'
            - Esxi: 'Linux/Services/esxi.md'
            - Plesk: 'Linux/Services/plesk.md'
  - macOS:
      - General: 'macOS/macGeneral.md'
      - Home Brew: 'macOS/brew.md'
      - MacOS Software: 'macOS/macSoftware.md'
      - Alftred Workflows: 'macOS/alfredWorkFlows.md'
  - Rasperry Pi:
      - General: 'rasperryPi/piGeneral.md'
      - Rasperry Pi 3 Tor Access Point: 'rasperryPi/TOR-Pi.md'
      - Rasperry Pi Magic Mirror: 'rasperryPi/MagicMirror.md'
  - Development:
      - Python: 'development/python.md'
  - Windows:
      - Windows General: 'windows/windowsGeneral.md'
  - Browsers Extensions:
      - Chrome: 'browsers/chromeExtensions.md'
      - Firefox: 'browsers/firefoxExtentions.md'
  - Android:
      - Useful Apps for Android: 'android/androidApps.md'
  - Penetration-Testing:
      - General: 'penTesting/penTestingGeneral.md'
      - Click-Jacking Test: 'penTesting/clickJacking.md'
      - Israel ID Generator & Validator: 'penTesting/IDD_Generator.md'
      - Kali Linux Modifications: 'penTesting/KaliLinux.md'
      - Installing Bettercap 1.6.2: 'penTesting/bettercao1.6.2.md'
  - Other:
      - General: 'general/generalLinks.md'
      - Gmail Mark As Read Script: 'general/gmailMarkAsRead.md'
      - Synology DSM : 'general/synologyGeneral.md'
      - Ubiquiti Networking: 'general/ubiquiti.md'
      - WiFi QR Generator: 'general/wifiQrGenerator.md'
  - Help:
      - Documinatation: 'help/documinatation.md'
      - Basic Cheat-Sheet: 'help/markdown_cheatsheet_basic.md'
      - MarkDown Cheat-Sheet: 'help/markdown_cheat-sheet.md'
      - Admonitions, callouts, sidebars: 'help/blocks.md'
      - GitHub: 'help/embedding/github.md'
      - Evernote: 'help/embedding/evernote.md'
      - Excel: 'help/embedding/excel.md'
      - Lucid: 'help/embedding/lucid.md'
      - Jing: 'help/embedding/jing.md'
      - Gists: 'help/embedding/gist.md'

  - About: 'about.md'

# Site information
site_name: '3os.org'
site_url: 'https://3os.org/'
site_description: 'Collocation of Guide, Technical knowledge, Security, Examples, Tips, at any operating system'
site_author: 'Stas Kosatuhin'

# Repository Link Editor
repo_name: 'fire1ce/3os.org'
repo_url: 'https://github.com/fire1ce/3os.org/'
edit_uri: 'edit/master/docs/'

# Theme Configuration
theme:
  language: en
  name: 'material'
  logo: 'assets/images/logo/baseline-scatter_plot-24px.svg_white.svg'
  favicon: 'assets/images/favicon.ico'
  palette:
    primary: 'teal'
    accent: 'teal'
  feature:
    tabs: 'true'
  # font:
  #   text: 'Roboto Slab'
  #   code: 'Roboto Mono'

# Social Links and Comments
extra:
#   disqus: '3os'
  social:
    - type: 'github'
      link: 'https://github.com/fire1ce'
    - type: 'linkedin'
      link: 'https://linkedin.com/in/stas-kosatuhin
'

# Markdown Rendering Extensions
markdown_extensions:
  - toc:
        permalink: True
        separator: "_"
  - admonition
  - codehilite
  - footnotes
  - meta
  - sane_lists
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.extra

# Google Analytics
google_analytics:
  - 'UA-122318911-1'
  - 'auto'

# Copyright
copyright: 'Copyright &copy; Stas Kosatuhin'